### ISSUE TITLE
LOGIN: app hangs on auth 'Cancel' with null error

### ISSUE THREAD

**Issue by jesscmoore** [anusii/notepod#66]
On pressing 'Cancel' in the authorisation pop up, the app crashes with null value error

It opens a login successful window, and the podnotes app hangs, whereas it should close the window and go back to the app login.

Tested on: macos, chrome, web - all hang on press 'Cancel'

![Image](https://github.com/anusii/podnotes/assets/5244819/f39fc81f-ddc2-403f-b3fc-9ff19139162e)

![Image](https://github.com/anusii/podnotes/assets/5244819/fd3b9154-f083-4ef9-81f1-3c3ca8d88b40)

chrome error:
```
flutter run -d chrome
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...             24.1s
This app is linked to the debug service: ws://127.0.0.1:53066/OFMrOr6dr_E=/ws
Debug service listening on ws://127.0.0.1:53066/OFMrOr6dr_E=/ws

🔥  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".

A Dart VM Service on Chrome is available at: http://127.0.0.1:53066/OFMrOr6dr_E=
The Flutter DevTools debugger and profiler on Chrome is available at:
http://127.0.0.1:9101?uri=http://127.0.0.1:53066/OFMrOr6dr_E=
Error: Unexpected null value.
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 297:3       throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 806:18  nullCheck
packages/solid_auth/src/openid/src/model/token_response.dart 25:66                get idToken
packages/solid_auth/src/openid/src/openid.dart 231:39                             <fn>
packages/solid_auth/src/openid/src/openid.dart 234:40                             generateLogoutUrl
packages/solid_auth/solid_auth_client.dart 220:34                                 authenticate
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50                <fn>
dart-sdk/lib/async/zone.dart 1661:54                                              runUnary
dart-sdk/lib/async/future_impl.dart 162:18                                        handleValue
dart-sdk/lib/async/future_impl.dart 838:44                                        handleValueCallback
dart-sdk/lib/async/future_impl.dart 867:13                                        _propagateToListeners
dart-sdk/lib/async/future_impl.dart 643:5                                         [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 713:7                                         callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                                  _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                                   _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7                <fn>
```

macos error
```
flutter run -d macos
Launching lib/main.dart on macOS in debug mode...
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00006000-0016091821C3401E }
{ platform:macOS, arch:x86_64, id:00006000-0016091821C3401E }
Building macOS application...
2023-12-11 07:28:51.218 podnotes[78857:1212617] WARNING: Secure coding is automatically enabled for restorable state! However, not on all supported macOS versions of this application. Opt-in to secure coding explicitly by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState:.
Syncing files to device macOS...                                   120ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

A Dart VM Service on macOS is available at: http://127.0.0.1:53358/5mQ79ARPK5Y=/
The Flutter DevTools debugger and profiler on macOS is available at:
http://127.0.0.1:9101?uri=http://127.0.0.1:53358/5mQ79ARPK5Y=/
flutter: server started 4400
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      TokenResponse.idToken (package:solid_auth/src/openid/src/model/token_response.dart:25:66)
#1      Credential.generateLogoutUrl (package:solid_auth/src/openid/src/openid.dart:231:31)
#2      authenticate (package:solid_auth/solid_auth_client.dart:220:35)
<asynchronous suspension>
#3      LoginScreen.createSolidLoginRow.<anonymous closure> (package:podnotes/login/screen.dart:201:19)
<asynchronous suspension>
```

**Comment by gjwgit** [comment]
Confirmed I get the same error on Linux.

**Comment by gjwgit** [comment]
Confirmed this still exists

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 5188 pos 7: '_history.any(_RouteEntry.isPresentPredicate)': Navigator has no active routes to replace.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:67:4)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:49:5)
#2      NavigatorState._pushReplacementEntry (package:flutter/src/widgets/navigator.dart:5188:7)
#3      NavigatorState.pushReplacement (package:flutter/src/widgets/navigator.dart:5132:5)
#4      Navigator.pushReplacement (package:flutter/src/widgets/navigator.dart:2402:34)
#5      _SolidLoginState.build.<anonymous closure>.navHomeScreen (package:solidpod/src/solid/login.dart:386:27)
#6      _SolidLoginState.build.<anonymous closure>.navigateToApp (package:solidpod/src/solid/login.dart:407:19)
<asynchronous suspension>
#7      _SolidLoginState.build.<anonymous closure> (package:solidpod/src/solid/login.dart:427:11)
<asynchronous suspension>


══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building Navigator-[GlobalObjectKey<NavigatorState>
_WidgetsAppState#90917](dirty, dependencies: [HeroControllerScope, InheritedCupertinoTheme,
UnmanagedRestorationScope, _InheritedTheme, _LocalizationsScope-[GlobalKey#1d72c]], state:
NavigatorState#8b8c2(tickers: tracking 1 ticker)):
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 5847 pos 12: '!_debugLocked':
is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=02_bug.yml

The relevant error-causing widget was:
  MaterialApp MaterialApp:file:///home/gjw/git/github/anusii/notepod/lib/main.dart:89:12

When the exception was thrown, this was the stack:
#2      NavigatorState.build (package:flutter/src/widgets/navigator.dart:5847:12)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:5823:27)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5715:15)
#5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5874:11)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:5427:7)
#7      BuildScope._tryRebuild (package:flutter/src/widgets/framework.dart:2694:15)
#8      BuildScope._flushDirtyElements (package:flutter/src/widgets/framework.dart:2752:11)
#9      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:3056:18)
#10     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1240:21)
#11     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:495:5)
#12     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1438:15)
#13     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1351:9)
#14     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1204:5)
#15     _invoke (dart:ui/hooks.dart:331:13)
#16     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:444:5)
#17     _drawFrame (dart:ui/hooks.dart:303:31)
(elided 2 frames from class _AssertionError)

════════════════════════════════════════════════════════════════════════════════════════════════════

```

**Comment by gjwgit** [comment]
Presumably a solidpod isue.

**Comment by anushkavidanage** [comment]
This is a solidpod issue. Created another task in `solidpod` https://github.com/anusii/solidpod/issues/283
