### ISSUE TITLE
BUG: Exception when there is a title but no note content

### ISSUE THREAD

**Issue by gjwgit** [anusii/notepod#91]
# Description

Start a new note, give it a title, then click SAVE NOTE without any content:

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RangeError (start): Invalid value: Only valid value is 0: -16
#0      RangeError.checkValidRange (dart:core/errors.dart:360:7)
#1      _TypedIntListMixin.sublist (dart:typed_data-patch/typed_data_patch.dart:535:31)
#2      PaddedBlockCipherImpl.doFinal (package:pointycastle/padded_block_cipher/padded_block_cipher_impl.dart:87:64)
#3      PaddedBlockCipherImpl.process (package:pointycastle/padded_block_cipher/padded_block_cipher_impl.dart:74:25)
#4      AES.encrypt (package:encrypt/src/algorithms/aes.dart:43:32)
#5      Encrypter.encryptBytes (package:encrypt/src/encrypter.dart:12:19)
#6      Encrypter.encrypt (package:encrypt/src/encrypter.dart:28:12)
#7      HomeState.build.<anonymous closure> (package:podnotes/home.dart:199:41)
<asynchronous suspension>
```

![Image](https://github.com/anusii/podnotes/assets/1681429/e374eab7-416c-41e0-9661-5594c1b7e676)

**Comment by anushkavidanage** [comment]
![Image](https://github.com/user-attachments/assets/8e8df81f-e321-4813-9509-0cd29ec43692)
