### ISSUE TITLE
SHARE: deleting existing permission failing with unhandled exception

### ISSUE THREAD

**Issue by jesscmoore** [anusii/notepod#97]
MYNOTES > click file Foo 3 > Click delete karen-reep's permissions is causing unhandled exception as removeSharedKey is failing

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Failed to create/update the shared file.
#0      removeSharedKey (package:podnotes/common/rest_api/res_permission.dart:843:5)
<asynchronous suspension>
#1      permissionRow.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:podnotes/notes/share_note.dart:152:53)
<asynchronous suspension>
```

![Image](https://github.com/anusii/podnotes/assets/5244819/5d4a3006-9a67-4ad9-8f2b-2ed967e47e18)

On return to the same file, see that karen-reep's permission was removed:

![Image](https://github.com/anusii/podnotes/assets/5244819/6ec30554-ae46-4ed6-b385-32fef25c971a)

**Comment by jesscmoore** [comment]
As this is very old, I was not expecting to replicate this bug, I now get a slightly different error.

Steps:
1. flutter run --debug -d macos
2. Login as jessicamoore
3. In My Notes open a note 'Bird data' which I know to be shared to my other pod account
4. Click delete icon to remove permissions for user jesscmoore
5. Confirm delete - app gets stuck for 1min+ with this error
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: RangeError (length): Invalid value: Only valid value is 0: 1
#0      getEncFileContent (package:solidpod/src/solid/api/rest_api.dart:68:42)
rest_api.dart:68
#1      removeSharedKey (package:solidpod/src/solid/api/revoke_permission_api.dart:157:28)
revoke_permission_api.dart:157
<asynchronous suspension>
#2      revokePermission (package:solidpod/src/solid/revoke_permission.dart:124:15)
revoke_permission.dart:124
<asynchronous suspension>
#3      buildPermDataTable.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:solidpod/src/widgets/file_permission_data_table.dart:126:31)
file_permission_data_table.dart:126
<asynchronous suspension>
```

**Comment by jesscmoore** [comment]
This issue can be closed as is already resolved by earlier updates to solidpod.

<img width="656" height="947" alt="Image" src="https://github.com/user-attachments/assets/c28b8906-bb42-4ea5-851b-e8b890bcc0ba" />

**Comment by gjwgit** [comment]
Thanks @jesscmoore
